name: crossnumber
description: An API and command line tool for solving Dice Nets puzzles
version: 2.0.0
repository: https://github.com/pohara60/dice-nets

environment:
  sdk: ">=3.0.0"

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  crossnumber_v2: bin/cross_number_v2.dart
